[en]
languageName = 'EN'
languageCode = 'en'

  [en.params]
  description = 'Actor and computer scientist'

[fr]
languageName = 'FR'
languageCode = 'fr'

  [fr.params]
  description = 'Acteur et informaticien'
