[en]
languageName = 'EN'
languageCode = 'en'

  [en.params]
  description = 'Actor and voice actor'

[fr]
languageName = 'FR'
languageCode = 'fr'

  [fr.params]
  description = 'Acteur et doubleur'

  indexdateformat='Mon 2 Jan 2006'
