[en]
languageName = 'EN'
languageCode = 'en'

  [en.params]
  description = 'Actor, voice actor and tenor singer'

[fr]
languageName = 'FR'
languageCode = 'fr'

  [fr.params]
  description = 'Acteur, doubleur et chanteur ténor'

  indexdateformat='Mon 2 Jan 2006'
