[en]
languageName = 'EN'
languageCode = 'en'

  [en.params]
  description = 'Apprentice actor and voice actor'

[fr]
languageName = 'FR'
languageCode = 'fr'

  [fr.params]
  description = 'Apprenti acteur et doubleur'
