[en]
languageName = 'EN'
languageCode = 'en'

  [en.params]
  description = 'Actor, voice actor and singer'

[fr]
languageName = 'FR'
languageCode = 'fr'

  [fr.params]
  description = 'Acteur, doubleur et chanteur'

  indexdateformat='Mon 2 Jan 2006'
