[en]
locale = 'en-US'
label = 'EN'
weight = 2

  [en.params]
  description = 'Actor and voice actor'

[fr]
locale = 'fr-CH'
label = 'FR'
weight = 1

  [fr.params]
  description = 'Acteur et doubleur'

  indexdateformat='Mon 2 Jan 2006'
  listdateformat='2 Jan'
