[[main]]
identifier = 'home'
name = 'Home'
pageRef = '/'
weight = 1

[[main]]
identifier = 'projects'
name = 'Projects'
pageRef = '/projects'
weight = 2

[[main]]
identifier = 'education'
name = 'Education'
pageRef = '/education'
weight = 3

[[main]]
identifier = 'about'
name = 'About'
pageRef = '/about'
weight = 4

