# Anatole theme

title = 'Timothée Andres'
author = 'Timothée Andres'
profilePicture = 'images/profile.png'
displayMode = 'dark'
contentratio = 0.65
disableTitleCapitalization = true
localizedDates = true
doNotLoadAnimations = true

images = ["images/profile.png"]

[[socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "mailto:acting@timotheeandr.es"

#[[socialIcons]]
#icon = "fas fa-camera"
#title = "Photos (coming soon...)"
#url = "#"
#
#[[socialIcons]]
#icon = "fas fa-clapperboard"
#title = "Showreel (coming soon...)"
#url = "#"
#
#[[socialIcons]]
#icon = "fas fa-microphone-lines"
#title = "Voice demo (coming soon...)"
#url = "#"

